### ISSUE TITLE
Error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by omid** [robertohuertasm/azure-function-rust#1]
Thanks for the library :D

I used your way and faced an error.
You can see the changed code and also the error in the following link:

https://gist.github.com/omid/b55fe742e8bacff0c34042218de5d363

Any idea about the error?

There are several topics related to this, but I couldn't fix it, like:
https://github.com/rust-lang/rust/issues/25289

**Comment by robertohuertasm** [comment]
What is your OS?

**Comment by omid** [comment]
Linux (Arch)

I ran it inside and outside of docker. Same problem.

**Comment by robertohuertasm** [comment]
Let me take a look. The other day I remember having the same issue but I don't know what I did to solve it! 🤦‍♂️

**Comment by robertohuertasm** [comment]
I cannot reproduce it... Have you tried doing `cargo clean`? If you try to build the project, does it work? I assume you're getting the error while doing `cargo func run`, is it right?

**Comment by omid** [comment]
yes

I faced this by running `cargo func run` and also `cargo build`

**Comment by omid** [comment]
Which os/distro do you have?

**Comment by robertohuertasm** [comment]
I tried to reproduce it both in a Mac and a pc with Ubuntu 18.04

**Comment by omid** [comment]
I installed a new fresh Ubuntu 18.04, upgrade it, install the latest Rust nightly and still face exactly the same problem with the code that _I've changed in the gist file_

Which version of OpenSSL do you have locally?

Can you send me your Cargo.lock also?

**Comment by robertohuertasm** [comment]
I get an openSSL error if I try your exact example. I'm trying to see what can be done. Does it work with the example I provided? Because I understood that this wasn't working for you, which doesn't seem to be the case.

**Comment by omid** [comment]
Your code works fine.
I followed your instruction, with a simple request in it, it doesn't work.

Actually my code doesn't work with your instruction.

**Comment by robertohuertasm** [comment]
Ok, now I got the same error as you. I got it wrong and thought you were having issues with the original code. I guess it would be helpful to open an issue in the [azure-functions-rs repo](https://github.com/peterhuene/azure-functions-rs), too.

**Comment by robertohuertasm** [comment]
This [issue from the reqwest repo](https://github.com/seanmonstar/reqwest/issues/173) seems to be related.

**Comment by robertohuertasm** [comment]
In the meantime you can use `hyper` to make your request.

**Comment by omid** [comment]
My simple code, without "azure-functions-rs", works fine.
Your code alone also works fine.

The combination has a problem!

**Comment by omid** [comment]
So I'll close this _issue_.

Check https://github.com/peterhuene/azure-functions-rs/issues/108
